apiVersion: apps/v1
kind: Deployment
metadata:
  name: userwebservice
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: userwebservice
          imagePullPolicy: Never
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"