apiVersion: apps/v1
kind: Deployment
metadata:
  name: csvwebservice
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: csvwebservice
          image: someregistry.io/test/csvwebservice:latest
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
      volumes:
      - name: config-volume
        configMap:
          name: prod-csvwebservice-app-config