apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: dev-
patches:
  - path: deployment-patch.yaml

patchesJson6902:
  - target:
      group: ""
      version: v1
      kind: Service
      name: csvwebservice
    path: service-patch.yaml

configMapGenerator:
  - name: csvwebservice-app-config
    files:
      - appsettings.json
    options:
      disableNameSuffixHash: true