apiVersion: apps/v1
kind: Deployment
metadata:
  name: csvwebservice
  labels:
    app: csvwebservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csvwebservice
  template:
    metadata:
      labels:
        app: csvwebservice
    spec:
      containers:
      - name: csvwebservice
        image: bison/csvwebservice:latest
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "TO_CHANGE"  # Change this value based on the environment
        resources:
          requests:
            memory: "50Mi"
            cpu: "50m"
          limits:
            memory: "100Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 10